kind: Pod
apiVersion: v1
metadata:
  name: spring-music
  labels:
    app: spring-music
    type: java
spec:
  containers:
  - name: spring-music
    image: humourmind/spring-music:blue
    imagePullPolicy: Always
    ports:
    - name: web
      containerPort: 8080
    resources:
      requests:
        memory: "768M"
        cpu: "250m"
      limits:
        memory: "1G"
        cpu: "750m"
    readinessProbe:
      httpGet:
        path: /actuator/health
        port: web
      initialDelaySeconds: 40
      periodSeconds: 5
      failureThreshold: 4
    livenessProbe:
      httpGet:
        path: /actuator/health
        port: web
      initialDelaySeconds: 60
      periodSeconds: 5
      failureThreshold: 3
